# Generated by Django 5.2.1 on 2025-05-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', '학생'), ('teacher', '교사'), ('admin', '관리자')], max_length=10),
        ),
    ]
