# Generated by Django 5.2.1 on 2025-05-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', '학생'), ('teacher', '교사'), ('admin', '관리자')], default='student', max_length=20),
        ),
    ]
