# Generated by Django 5.2.1 on 2025-08-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='년도')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_highlight', models.BooleanField(default=False, verbose_name='하이라이트 표시')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '성과',
                'verbose_name_plural': '성과',
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('portfolio', '심슨 포트폴리오'), ('interview', '심슨 인터뷰'), ('contest', '심슨 콘테스트')], max_length=20, verbose_name='활동 유형')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='설명')),
                ('sub_description', models.CharField(blank=True, max_length=300, verbose_name='부가 설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='이미지')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '학원 활동',
                'verbose_name_plural': '학원 활동',
                'ordering': ['activity_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='부제목')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider/', verbose_name='이미지')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '메인 슬라이더',
                'verbose_name_plural': '메인 슬라이더',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Philosophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10, verbose_name='아이콘 (이모지)')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '교육신념',
                'verbose_name_plural': '교육신념',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('news', 'News & Debate'), ('middle', '중등 내신 자료'), ('high', '고등 내신 자료')], max_length=20, verbose_name='프로그램 유형')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='programs/', verbose_name='이미지 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='programs/', verbose_name='이미지 2')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '프로그램',
                'verbose_name_plural': '프로그램',
                'ordering': ['program_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SpecialSchoolResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100, verbose_name='특목고')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='학과')),
                ('student_name', models.CharField(max_length=50, verbose_name='학생 이름')),
                ('middle_school', models.CharField(max_length=100, verbose_name='중학교')),
                ('year', models.IntegerField(verbose_name='합격년도')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '특목고 합격자',
                'verbose_name_plural': '특목고 합격자',
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UniversityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100, verbose_name='대학교')),
                ('department', models.CharField(max_length=100, verbose_name='학과')),
                ('student_name', models.CharField(max_length=50, verbose_name='학생 이름')),
                ('high_school', models.CharField(max_length=100, verbose_name='고등학교')),
                ('branch', models.CharField(blank=True, max_length=50, verbose_name='지점')),
                ('year', models.IntegerField(verbose_name='합격년도')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '대학 합격자',
                'verbose_name_plural': '대학 합격자',
                'ordering': ['-year', 'order'],
            },
        ),
    ]
